import tkinter as tk
from tkinter import ttk, messagebox
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
import textwrap
import datetime
import os

# -----------------------------
# CAREER RULES (simple lookup)
# -----------------------------
CAREER_RULES = {
    "Software Engineer": {
        "keywords": ["programming", "technology", "logic", "math", "algorithms", "coding"],
        "suggestion": "Build coding projects, study algorithms/data-structures and contribute to real apps."
    },
    "Doctor": {
        "keywords": ["biology", "medicine", "helping people", "care", "health"],
        "suggestion": "Pursue medical studies, volunteer in healthcare settings and prepare for entrance exams."
    },
    "Graphic Designer": {
        "keywords": ["creativity", "art", "design", "visual", "ui", "ux"],
        "suggestion": "Create a design portfolio, learn tools like Figma/Illustrator, and study UX fundamentals."
    },
    "Teacher": {
        "keywords": ["teaching", "communication", "patience", "mentoring", "education"],
        "suggestion": "Gain tutoring experience, learn pedagogy, and build strong communication skills."
    },
    "Entrepreneur": {
        "keywords": ["business", "leadership", "risk taking", "management", "startup"],
        "suggestion": "Learn business planning, networking, and try small ventures to gain experience."
    }
}

# -----------------------------
# Recommendation engine
# -----------------------------
def evaluate_careers(facts):
    # facts: list of words/phrases
    scores = {}
    lowfacts = [f.lower() for f in facts]
    for career, info in CAREER_RULES.items():
        score = 0
        for kw in info["keywords"]:
            for f in lowfacts:
                if kw in f or f in kw:
                    score += 1
        scores[career] = score
    ranked = sorted(scores.items(), key=lambda x: x[1], reverse=True)
    recommendations = []
    for career, score in ranked:
        if score > 0:
            recommendations.append({
                "career": career,
                "score": score,
                "suggestion": CAREER_RULES[career]["suggestion"]
            })
    if not recommendations:
        recommendations.append({
            "career": "General Career Counseling Recommended",
            "score": 0,
            "suggestion": "Explore diverse fields, take assessments and speak with professionals."
        })
    return recommendations

# -----------------------------
# PDF generation (includes conversation)
# -----------------------------
def generate_pdf(user_info, conversation, recommendations):
    safe_name = "".join(c for c in user_info.get("name", "User") if c.isalnum() or c in (' ', '_')).strip().replace(' ', '_') or "User"
    filename = f"{safe_name}_Career_Report_{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    doc = SimpleDocTemplate(filename, pagesize=A4, rightMargin=36, leftMargin=36, topMargin=36, bottomMargin=36)

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle('title', parent=styles['Heading1'], alignment=TA_CENTER, textColor=colors.HexColor('#0d47a1'), fontSize=20)
    subtitle_style = ParagraphStyle('subtitle', parent=styles['Heading2'], alignment=TA_LEFT, textColor=colors.HexColor('#1565c0'), fontSize=14)
    normal = ParagraphStyle('normal', parent=styles['Normal'], fontSize=10, leading=13)
    wrap_style = ParagraphStyle('wrap', parent=styles['Normal'], fontSize=10, leading=12, alignment=TA_LEFT)

    elems = []
    elems.append(Paragraph("🌟 Personalized Career Guidance Report", title_style))
    elems.append(Spacer(1, 8))
    elems.append(Paragraph("Generated by CareerWizard", normal))
    elems.append(Spacer(1, 12))

    # Personal info block
    elems.append(Paragraph("📝 Personal Information", subtitle_style))
    personal_info_text = ""
    for k in ("name", "age", "gender", "education", "preferred_country", "salary_expectation"):
        if user_info.get(k):
            personal_info_text += f"<b>{k.replace('_',' ').title()}:</b> {user_info[k]}<br/>"
    elems.append(Paragraph(personal_info_text, normal))
    elems.append(Spacer(1, 8))

    # Preferences & answers
    elems.append(Paragraph("💡 Responses & Preferences", subtitle_style))
    # Use conversation list of (question, answer)
    for q, a in conversation:
        # wrap long text
        text = f"<b>{q}</b>: {a}"
        elems.append(Paragraph(text, wrap_style))
    elems.append(Spacer(1, 12))

    # Most suitable
    best = recommendations[0]
    elems.append(Paragraph("🏆 Most Suitable Career", subtitle_style))
    elems.append(Paragraph(f"<b>{best['career']}</b> (Score: {best['score']})<br/>{best['suggestion']}", wrap_style))
    elems.append(Spacer(1, 12))

    # All recommendations table
    elems.append(Paragraph("🎯 Career Recommendations", subtitle_style))
    data = [["Career Path", "Suitability Score", "Suggestions"]]
    for rec in recommendations:
        # wrap suggestion text to avoid overflow in table
        suggestion = rec["suggestion"]
        data.append([rec["career"], str(rec["score"]), Paragraph(suggestion, wrap_style)])

    table = Table(data, colWidths=[150, 70, 280], repeatRows=1)
    table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#1565c0')),
        ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,-1), 9),
        ('ALIGN', (0,0), (1,-1), 'CENTER'),
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ('GRID', (0,0), (-1,-1), 0.4, colors.grey),
        ('BACKGROUND', (0,1), (-1,-1), colors.whitesmoke),
        ('LEFTPADDING', (0,0), (-1,-1), 6),
        ('RIGHTPADDING', (0,0), (-1,-1), 6),
        ('TOPPADDING', (0,0), (-1,-1), 6),
        ('BOTTOMPADDING', (0,0), (-1,-1), 6),
    ]))
    elems.append(table)
    elems.append(Spacer(1, 10))

    elems.append(Paragraph("💡 Note: This report is for guidance only.", normal))
    elems.append(Spacer(1, 6))
    doc.build(elems)

    messagebox.showinfo("PDF Created", f"PDF report saved as:\n{os.path.abspath(filename)}")
    return filename

# -----------------------------
# GUI: Multi-step wizard
# -----------------------------
class StepFrame(tk.Frame):
    def __init__(self, master, **kwargs):
        super().__init__(master, **kwargs)
        self.configure(bg='#ffffff', bd=0, highlightthickness=0)

class CareerWizard(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title("Career Wizard - Enhanced")
        self.geometry("820x640")
        self.resizable(False, False)
        self.configure(bg='#e6eefc')

        # central card (glass look)
        self.card = tk.Frame(self, bg='#ffffff', bd=0, relief='flat')
        self.card.place(relx=0.5, rely=0.5, anchor='center', width=760, height=560)

        # header
        header = tk.Label(self.card, text="👋 Hey Buddy! Let's Explore Your Career Path", bg='#ffffff',
                          fg='#0d47a1', font=("Helvetica", 16, "bold"))
        header.pack(pady=(14, 6))

        subtitle = tk.Label(self.card, text="Answer a few questions — we'll generate a personalized report.", bg='#ffffff',
                            fg='#37474f', font=("Helvetica", 10))
        subtitle.pack(pady=(0, 12))

        # container for steps
        self.step_container = tk.Frame(self.card, bg='#ffffff')
        self.step_container.pack(fill='both', expand=True, padx=18, pady=6)

        # navigation buttons area
        nav_frame = tk.Frame(self.card, bg='#ffffff')
        nav_frame.pack(fill='x', padx=18, pady=(0,12))

        self.back_btn = ttk.Button(nav_frame, text="◀ Back", command=self.prev_step)
        self.back_btn.pack(side='left')
        self.next_btn = ttk.Button(nav_frame, text="Next ▶", command=self.next_step)
        self.next_btn.pack(side='right')

        # progress label
        self.progress_var = tk.StringVar()
        self.progress_label = tk.Label(nav_frame, textvariable=self.progress_var, bg='#ffffff', fg='#37474f')
        self.progress_label.pack(side='left', padx=10)

        # state
        self.steps = []
        self.current = 0
        self.user_info = {}
        self.conversation = []  # list of (question, answer)

        self.create_steps()
        self.show_step(0)

    def create_steps(self):
        # Step 0: Personal Info
        s0 = StepFrame(self.step_container, bg='#ffffff')
        tk.Label(s0, text="Personal Information", font=("Helvetica", 12, "bold"), bg='#ffffff', fg='#0d47a1').pack(anchor='w', pady=(6,4))
        self.name_var = tk.StringVar()
        self.age_var = tk.StringVar()
        self.gender_var = tk.StringVar()
        self.edu_var = tk.StringVar()
        self.country_var = tk.StringVar()
        self.salary_var = tk.StringVar()

        self._add_labeled_entry(s0, "Full Name:", self.name_var)
        self._add_labeled_entry(s0, "Age:", self.age_var)
        self._add_labeled_entry(s0, "Gender:", self.gender_var)
        self._add_labeled_entry(s0, "Education Level (e.g., 12th/Bachelor):", self.edu_var)
        self._add_labeled_entry(s0, "Preferred Country (optional):", self.country_var)
        self._add_labeled_entry(s0, "Expected Salary (optional):", self.salary_var)

        self.steps.append(s0)

        # Step 1: Interests & Skills
        s1 = StepFrame(self.step_container, bg='#ffffff')
        tk.Label(s1, text="Interests & Skills", font=("Helvetica", 12, "bold"), bg='#ffffff', fg='#0d47a1').pack(anchor='w', pady=(6,4))
        self.interests_var = tk.StringVar()
        self.skills_var = tk.StringVar()
        self.fav_subjects_var = tk.StringVar()
        self.learning_style_var = tk.StringVar()

        self._add_labeled_entry(s1, "Interests (comma separated):", self.interests_var)
        self._add_labeled_entry(s1, "Key Skills (comma separated):", self.skills_var)
        self._add_labeled_entry(s1, "Favourite Subjects:", self.fav_subjects_var)
        self._add_labeled_entry(s1, "Learning Style (visual/auditory/kinesthetic):", self.learning_style_var)

        self.steps.append(s1)

        # Step 2: Strengths & Weaknesses
        s2 = StepFrame(self.step_container, bg='#ffffff')
        tk.Label(s2, text="Strengths, Weaknesses & Personality", font=("Helvetica", 12, "bold"), bg='#ffffff', fg='#0d47a1').pack(anchor='w', pady=(6,4))
        self.strengths_var = tk.StringVar()
        self.weaknesses_var = tk.StringVar()
        self.personality_var = tk.StringVar()

        self._add_labeled_entry(s2, "Top Strengths (comma separated):", self.strengths_var)
        self._add_labeled_entry(s2, "Top Weaknesses (comma separated):", self.weaknesses_var)
        self._add_labeled_entry(s2, "Personality Traits (comma separated):", self.personality_var)

        self.steps.append(s2)

        # Step 3: Preferences & Goals
        s3 = StepFrame(self.step_container, bg='#ffffff')
        tk.Label(s3, text="Work Preferences & Goals", font=("Helvetica", 12, "bold"), bg='#ffffff', fg='#0d47a1').pack(anchor='w', pady=(6,4))
        self.env_var = tk.StringVar()
        self.role_pref_var = tk.StringVar()
        self.goal_var = tk.StringVar()
        self.study_time_var = tk.StringVar()

        self._add_labeled_entry(s3, "Preferred Work Environment (office/remote/field):", self.env_var)
        self._add_labeled_entry(s3, "Preferred Role (e.g., developer, researcher):", self.role_pref_var)
        self._add_labeled_entry(s3, "Career Goal (short/long-term):", self.goal_var)
        self._add_labeled_entry(s3, "Best Study Time (morning/evening/night):", self.study_time_var)

        self.steps.append(s3)

        # Step 4: Behavioral questions (yes/no)
        s4 = StepFrame(self.step_container, bg='#ffffff')
        tk.Label(s4, text="Quick Behavioral Questions", font=("Helvetica", 12, "bold"), bg='#ffffff', fg='#0d47a1').pack(anchor='w', pady=(6,4))

        self.logical_var = tk.StringVar(value="no")
        self.helping_var = tk.StringVar(value="no")
        self.leadership_var = tk.StringVar(value="no")
        self.risk_var = tk.StringVar(value="no")

        self._add_radio_question(s4, "Do you enjoy solving logical problems?", self.logical_var)
        self._add_radio_question(s4, "Do you enjoy helping people directly?", self.helping_var)
        self._add_radio_question(s4, "Are you comfortable leading a team?", self.leadership_var)
        self._add_radio_question(s4, "Do you like taking calculated risks (entrepreneurship)?", self.risk_var)

        self.steps.append(s4)

        # Step 5: Additional input / achievements / hobbies
        s5 = StepFrame(self.step_container, bg='#ffffff')
        tk.Label(s5, text="Hobbies, Achievements & Extra Info", font=("Helvetica", 12, "bold"), bg='#ffffff', fg='#0d47a1').pack(anchor='w', pady=(6,4))
        self.hobbies_var = tk.StringVar()
        self.achievement_var = tk.StringVar()
        self.extra_var = tk.StringVar()

        self._add_labeled_entry(s5, "Hobbies (comma separated):", self.hobbies_var)
        self._add_labeled_entry(s5, "Biggest Achievement (brief):", self.achievement_var)
        self._add_labeled_entry(s5, "Anything else you'd like to share:", self.extra_var)

        self.steps.append(s5)

        # Step 6: Review & Submit
        s6 = StepFrame(self.step_container, bg='#ffffff')
        tk.Label(s6, text="Review & Generate Report", font=("Helvetica", 12, "bold"), bg='#ffffff', fg='#0d47a1').pack(anchor='w', pady=(6,4))
        self.review_text = tk.Text(s6, width=84, height=16, wrap='word', bg='#fbfbff')
        self.review_text.pack(pady=6)
        tk.Label(s6, text="When you click 'Submit', a PDF will be generated with your responses and recommendations.", bg='#ffffff').pack(pady=(4,0))
        self.steps.append(s6)

    # utility widgets
    def _add_labeled_entry(self, parent, label_text, var):
        frm = tk.Frame(parent, bg='#ffffff')
        frm.pack(fill='x', pady=6)
        lbl = tk.Label(frm, text=label_text, anchor='w', bg='#ffffff', fg='#37474f')
        lbl.pack(anchor='w')
        ent = ttk.Entry(frm, textvariable=var, width=80)
        ent.pack(anchor='w', pady=4)

    def _add_radio_question(self, parent, question, var):
        frm = tk.Frame(parent, bg='#ffffff')
        frm.pack(fill='x', pady=6)
        lbl = tk.Label(frm, text=question, anchor='w', bg='#ffffff', fg='#37474f')
        lbl.pack(anchor='w')
        opt_frame = tk.Frame(frm, bg='#ffffff')
        opt_frame.pack(anchor='w', pady=4)
        ttk.Radiobutton(opt_frame, text="Yes", variable=var, value="yes").pack(side='left', padx=(0,12))
        ttk.Radiobutton(opt_frame, text="No", variable=var, value="no").pack(side='left')

    def show_step(self, idx):
        # remove current children
        for child in self.step_container.winfo_children():
            child.pack_forget()

        frame = self.steps[idx]
        frame.pack(fill='both', expand=True)
        self.current = idx
        self._update_nav()
        # small animation: fade-like by setting alpha quickly (simulated)
        self._animate_frame(frame)

        # If review step, populate review text
        if idx == len(self.steps) - 1:
            self.populate_review()

    def _animate_frame(self, frame):
        # simple visual flash — change bg briefly (small animation)
        orig = frame.cget('bg')
        frame.configure(bg='#f7fbff')
        self.after(120, lambda: frame.configure(bg=orig))

    def _update_nav(self):
        total = len(self.steps)
        self.progress_var.set(f"Step {self.current+1} of {total}")
        if self.current == 0:
            self.back_btn.config(state='disabled')
        else:
            self.back_btn.config(state='normal')

        if self.current == len(self.steps) - 1:
            self.next_btn.config(text="Submit", command=self.submit)
        else:
            self.next_btn.config(text="Next ▶", command=self.next_step)

    def next_step(self):
        if not self._validate_current():
            return
        if self.current < len(self.steps) - 1:
            self.show_step(self.current + 1)

    def prev_step(self):
        if self.current > 0:
            self.show_step(self.current - 1)

    def _validate_current(self):
        # basic per-step validation (ensure required fields filled)
        if self.current == 0:
            if not self.name_var.get().strip():
                messagebox.showerror("Validation", "Please enter your name.")
                return False
            if not self.age_var.get().strip():
                messagebox.showerror("Validation", "Please enter your age.")
                return False
        if self.current == 1:
            if not self.interests_var.get().strip():
                messagebox.showerror("Validation", "Please list at least one interest.")
                return False
        return True

    def populate_review(self):
        self.review_text.delete('1.0', tk.END)
        pairs = [
            ("Full Name", self.name_var.get()),
            ("Age", self.age_var.get()),
            ("Gender", self.gender_var.get()),
            ("Education", self.edu_var.get()),
            ("Preferred Country", self.country_var.get()),
            ("Salary Expectation", self.salary_var.get()),
            ("Interests", self.interests_var.get()),
            ("Skills", self.skills_var.get()),
            ("Favourite Subjects", self.fav_subjects_var.get()),
            ("Learning Style", self.learning_style_var.get()),
            ("Strengths", self.strengths_var.get()),
            ("Weaknesses", self.weaknesses_var.get()),
            ("Personality", self.personality_var.get()),
            ("Preferred Environment", self.env_var.get()),
            ("Preferred Role", self.role_pref_var.get()),
            ("Career Goal", self.goal_var.get()),
            ("Study Time", self.study_time_var.get()),
            ("Logical problems?", self.logical_var.get()),
            ("Help people?", self.helping_var.get()),
            ("Leadership?", self.leadership_var.get()),
            ("Risk taking?", self.risk_var.get()),
            ("Hobbies", self.hobbies_var.get()),
            ("Achievement", self.achievement_var.get()),
            ("Extra", self.extra_var.get())
        ]
        text = ""
        for k, v in pairs:
            text += f"{k}: {v}\n"
        self.review_text.insert(tk.END, text)

    def collect_answers(self):
        # Build user_info and conversation list
        self.user_info = {
            "name": self.name_var.get().strip(),
            "age": self.age_var.get().strip(),
            "gender": self.gender_var.get().strip(),
            "education": self.edu_var.get().strip(),
            "preferred_country": self.country_var.get().strip(),
            "salary_expectation": self.salary_var.get().strip(),
            "interests": self.interests_var.get().strip(),
            "skills": self.skills_var.get().strip(),
            "fav_subjects": self.fav_subjects_var.get().strip(),
            "learning_style": self.learning_style_var.get().strip(),
            "strengths": self.strengths_var.get().strip(),
            "weaknesses": self.weaknesses_var.get().strip(),
            "personality": self.personality_var.get().strip(),
            "preferred_environment": self.env_var.get().strip(),
            "preferred_role": self.role_pref_var.get().strip(),
            "goal": self.goal_var.get().strip(),
            "study_time": self.study_time_var.get().strip(),
            "logical": self.logical_var.get(),
            "helping": self.helping_var.get(),
            "leadership": self.leadership_var.get(),
            "risk": self.risk_var.get(),
            "hobbies": self.hobbies_var.get().strip(),
            "achievement": self.achievement_var.get().strip(),
            "extra": self.extra_var.get().strip()
        }

        conv = []
        # list questions and answers in order
        qa_pairs = [
            ("Full Name", self.user_info["name"]),
            ("Age", self.user_info["age"]),
            ("Gender", self.user_info["gender"]),
            ("Education", self.user_info["education"]),
            ("Preferred Country", self.user_info["preferred_country"]),
            ("Salary Expectation", self.user_info["salary_expectation"]),
            ("Interests", self.user_info["interests"]),
            ("Skills", self.user_info["skills"]),
            ("Favourite Subjects", self.user_info["fav_subjects"]),
            ("Learning Style", self.user_info["learning_style"]),
            ("Strengths", self.user_info["strengths"]),
            ("Weaknesses", self.user_info["weaknesses"]),
            ("Personality Traits", self.user_info["personality"]),
            ("Preferred Work Environment", self.user_info["preferred_environment"]),
            ("Preferred Role", self.user_info["preferred_role"]),
            ("Career Goal", self.user_info["goal"]),
            ("Study Time", self.user_info["study_time"]),
            ("Enjoy solving logical problems?", self.user_info["logical"]),
            ("Enjoy helping people directly?", self.user_info["helping"]),
            ("Comfortable leading a team?", self.user_info["leadership"]),
            ("Like taking risks (entrepreneurship)?", self.user_info["risk"]),
            ("Hobbies", self.user_info["hobbies"]),
            ("Biggest Achievement", self.user_info["achievement"]),
            ("Extra Info", self.user_info["extra"])
        ]
        for q, a in qa_pairs:
            conv.append((q, a))
        self.conversation = conv
        return self.user_info, self.conversation

    def submit(self):
        # final validation
        if not self.name_var.get().strip():
            messagebox.showerror("Missing", "Please enter your name.")
            self.show_step(0)
            return
        # collect answers
        user_info, conversation = self.collect_answers()
        # prepare facts for recommendation: combine many text fields
        facts = []
        for k in ("interests", "skills", "strengths", "weaknesses", "personality", "hobbies", "fav_subjects", "preferred_role"):
            val = user_info.get(k) or ""
            parts = [p.strip().lower() for p in val.split(",") if p.strip()]
            facts.extend(parts)
        # include boolean answers
        if user_info.get("logical") == "yes":
            facts.append("logic")
        if user_info.get("helping") == "yes":
            facts.append("helping people")
        if user_info.get("leadership") == "yes":
            facts.append("leadership")
        if user_info.get("risk") == "yes":
            facts.append("entrepreneur")

        recommendations = evaluate_careers(facts)

        # Generate PDF
        generate_pdf(user_info, conversation, recommendations)
        # Optionally: open the folder or show success (already messagebox inside)
        # reset or close
        if messagebox.askyesno("Done", "Do you want to fill another profile?"):
            self.reset_all()
            self.show_step(0)
        else:
            self.destroy()

    def reset_all(self):
        # reset variables
        for var in [self.name_var, self.age_var, self.gender_var, self.edu_var, self.country_var, self.salary_var,
                    self.interests_var, self.skills_var, self.fav_subjects_var, self.learning_style_var,
                    self.strengths_var, self.weaknesses_var, self.personality_var, self.env_var, self.role_pref_var,
                    self.goal_var, self.study_time_var, self.logical_var, self.helping_var, self.leadership_var,
                    self.risk_var, self.hobbies_var, self.achievement_var, self.extra_var]:
            try:
                var.set("")
            except:
                pass

if __name__ == "__main__":
    app = CareerWizard()
    app.mainloop()
